            -- I. MySQL et les bases du langage SQL
            -- ------------------------------------
                -- I.1. Introduction
                -- I.2. Installation de MySQL
                -- I.3. Les types de donnees
                -- I.4. Creation d'une base de donnees
                -- I.5. Creation de tables
                -- I.6. Modification d'une table
                -- I.7. Insertion de donnees
                -- I.8. Selection de donnees
                -- I.9. Elargir la possibilite de la clause WHERE
                -- I.10. Suppression et modification de donnees
